# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!
workspace 'NewsHack'
xcodeproj 'NewsHack.xcodeproj'

pod 'AFNetworking', '~> 2.0'
pod 'Bolts'
pod 'Haneke', '~> 1.0'
pod 'FXBlurView', '~> 1.6'
